# Generated by Django 4.1.4 on 2022-12-29 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("username", models.CharField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=20)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("is_superuser", models.IntegerField(blank=True, null=True)),
                ("is_active", models.IntegerField(blank=True, null=True)),
                ("is_staff", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "auth_user",
            },
        ),
        migrations.CreateModel(
            name="VideoMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_preprocess",
                    models.FileField(default="", upload_to="archive/video/%Y%m%d"),
                ),
                ("url_postprocess", models.TextField(default="")),
                ("created_at", models.DateTimeField()),
                (
                    "uploader",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_video",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashtag", models.CharField(default="", max_length=30)),
                ("created_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scrolls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Untitled", max_length=100)),
                ("created_at", models.DateTimeField()),
                ("height", models.IntegerField(default=0)),
                ("length", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_scrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        related_name="likes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "mention",
                    models.ManyToManyField(
                        related_name="mentioned_in", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.videomedia",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(related_name="mentioned_in", to="main.tag"),
                ),
            ],
        ),
    ]
