# Generated by Django 4.1.5 on 2023-06-05 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrolls',
            name='reported_by',
            field=models.ManyToManyField(null=True, related_name='reported_scrolls', to=settings.AUTH_USER_MODEL),
        ),
    ]
