# Generated by Django 4.1.5 on 2023-06-05 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_scrolls_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='remix',
            name='reported_by',
            field=models.ManyToManyField(null=True, related_name='reported_remixes', to=settings.AUTH_USER_MODEL),
        ),
    ]
