# Generated by Django 4.1.4 on 2022-12-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_scrolls_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
