# Generated by Django 4.1.4 on 2022-12-31 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cell_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrolls',
            name='uploader',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
