# Generated by Django 4.1.5 on 2023-06-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remix_saved_by_scrolls_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
