# Generated by Django 4.1.5 on 2023-06-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='influencer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
