# Generated by Django 4.1.5 on 2023-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userinteraction_taginteraction_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrolls',
            name='ipfs_hash',
            field=models.CharField(default='', max_length=100),
        ),
    ]
