# Generated by Django 4.1.5 on 2023-03-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_scrolls_ipfs_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrolls',
            name='scrolls_url',
            field=models.CharField(default='', max_length=400),
        ),
    ]
