# Generated by Django 4.1.5 on 2023-06-27 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_dailyvisit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.IntegerField(default=1)),
                ('external_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier', to='main.externaluploader')),
                ('internal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=255)),
                ('sound_type', models.CharField(default='event', max_length=255)),
                ('is_downloaded', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.FloatField()),
                ('loopable', models.IntegerField(default=0)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('tag', models.ManyToManyField(related_name='tagged_sounds', to='main.tag')),
                ('used_in', models.ManyToManyField(related_name='featured_sounds', to='main.scrolls')),
            ],
        ),
    ]
