# Generated by Django 4.1.5 on 2023-03-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_scrolls_scrolls_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('scrolls', models.ManyToManyField(default=None, null=True, related_name='highlight', to='main.scrolls')),
            ],
        ),
    ]
