# Generated by Django 4.1.5 on 2023-06-28 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_externaluploader_sounduploader_sound'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedScrollsStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.FloatField(default=0)),
                ('timeline', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('scroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scrolls')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.FloatField(blank=True, default=0, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewed_scrolls_statistics', models.ManyToManyField(related_name='sessions', to='main.viewedscrollsstatistic')),
            ],
        ),
    ]
