# Generated by Django 4.1.5 on 2023-04-15 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(default=4)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
