# Generated by Django 4.1.5 on 2023-06-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_viewedscrollsstatistic_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewedscrollsstatistic',
            old_name='scroll',
            new_name='scrolls',
        ),
    ]
