# Generated by Django 4.1.5 on 2023-05-10 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mockingJae_back.storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='scrolls',
            name='scrolls_dir',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Remix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('remix_directory', models.FileField(null=True, storage=mockingJae_back.storages.S3Storage(bucket_name='scrollsbucket01', custom_domain=None), upload_to='remixes/%Y%m%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scrolls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.scrolls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
