# Generated by Django 4.1.5 on 2023-06-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_session_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_sounds', to='main.sounduploader'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='used_in',
            field=models.ManyToManyField(related_name='featuring_sounds', to='main.scrolls'),
        ),
    ]
