# Generated by Django 4.1.5 on 2023-06-29 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sound_uploader_alter_sound_used_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounduploader',
            name='external_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifier', to='main.externaluploader'),
        ),
        migrations.AlterField(
            model_name='sounduploader',
            name='internal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
