# Generated by Django 4.1.5 on 2023-06-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_sounduploader_external_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='internal_id',
            field=models.IntegerField(default=0),
        ),
    ]
