# Generated by Django 4.1.5 on 2023-07-01 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sound_internal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='sound',
            name='used_in',
        ),
        migrations.CreateModel(
            name='SoundScrollsJoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_joined', to='main.sound')),
                ('events', models.ManyToManyField(related_name='joint', to='main.event')),
                ('scrolls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_joints', to='main.scrolls')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_joined', to='main.sound'),
        ),
    ]
