# Generated by Django 4.1.5 on 2023-05-13 04:40

from django.db import migrations, models
import mockingJae_back.storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image/default.png', null=True, storage=mockingJae_back.storages.S3Storage(bucket_name='scrollsbucket01', custom_domain=None), upload_to='profile_image'),
        ),
    ]
