# Generated by Django 4.1.5 on 2023-05-14 08:36

from django.db import migrations, models
import mockingJae_back.storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remix',
            name='remix_directory',
            field=models.CharField(default='/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image/default.png', null=True, storage=mockingJae_back.storages.S3Storage(bucket_name='mockingjae-test-bucket', custom_domain=None), upload_to='profile_image'),
        ),
    ]
