# Generated by Django 4.1.5 on 2023-05-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_remix_remix_directory_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='remix',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='remix',
            name='remix_directory',
            field=models.CharField(default='/', max_length=500, null=True),
        ),
    ]
