# Generated by Django 4.1.5 on 2023-05-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_remix_managers_alter_remix_remix_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='remix',
            name='uploaded_to_s3',
            field=models.IntegerField(default=0),
        ),
    ]
