# Generated by Django 4.1.5 on 2023-05-20 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_user_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('forward_audio_url', models.CharField(max_length=500)),
                ('backward_audio_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scrolls',
            name='audios',
            field=models.ManyToManyField(null=True, related_name='used_in', to='main.audiomodel'),
        ),
    ]
