# Generated by Django 4.1.4 on 2023-05-21 07:23

from django.db import migrations, models
import mockingJae_back.storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_scrolls_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image/default.png', null=True, storage=mockingJae_back.storages.S3Storage(bucket_name='mockingjae-test-bucket', custom_domain=None), upload_to='profile_image'),
        ),
    ]
