# Generated by Django 4.1.4 on 2023-05-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomedia',
            name='public_url',
            field=models.CharField(default='/', max_length=400, null=True),
        ),
    ]
