# Generated by Django 4.1.5 on 2023-05-22 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_videomedia_public_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='remix',
            name='length',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scrolls',
            name='saved_by',
            field=models.ManyToManyField(null=True, related_name='saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrolls',
            name='scrolled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrolls',
            name='shared_by',
            field=models.ManyToManyField(null=True, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
