# Generated by Django 4.1.5 on 2023-05-28 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mockingJae_back.storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remix_length_scrolls_saved_by_scrolls_scrolled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tagger',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videomedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=mockingJae_back.storages.S3Storage(bucket_name='mockingjae-test-bucket', custom_domain=None), upload_to='thumbnails/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='scrolls',
            name='uploaded',
            field=models.IntegerField(default=1),
        ),
    ]
